// Loads the canonical skill-matrix feed (data/skill-matrix.json), which is
// regenerated by scripts/publish/generate_skill_matrix.py from the fleet eval
// results and committed to the repo. This is the single source of truth for
// both /test/results and the homepage leaderboard.
//
// Regenerate + commit this JSON (via the publisher) whenever new eval runs land.
import feed from "@/data/skill-matrix.json";

export type SkillMatrixSummary = {
  model: string;
  machine: string;
  tests: number;
  capable: number;
  avgQuality: number | null;
  avgAccuracy: number | null;
  medianSpeedS: number | null;
  capableRate: number;
  lastTested: string;
  ttftMs?: number | null;
};

export type SkillMatrixRun = {
  model: string;
  machine: string;
  category: string;
  testId: string;
  capable: boolean | null;
  quality: number | null;
  accuracy: number | null;
  speedSeconds: number | null;
  outTokens: number | null;
  testedAt: string;
  ttftMs?: number | null;
};

export type SkillMatrixFeed = {
  schemaVersion: number;
  generatedAt: string;
  source: string;
  totalRuns: number;
  skippedFiles: number;
  summary: SkillMatrixSummary[];
  top5: SkillMatrixSummary[];
  runs: SkillMatrixRun[];
};

const data = feed as SkillMatrixFeed;

export const summary: SkillMatrixSummary[] = data.summary;
export const runs: SkillMatrixRun[] = data.runs;
export const top5: SkillMatrixSummary[] = data.top5;
export const feedMeta = {
  generatedAt: data.generatedAt,
  totalRuns: data.totalRuns,
  source: data.source,
};
