import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
const { marked } = await import(process.env.MARKED_PATH ? pathToFileURL(process.env.MARKED_PATH).href : 'marked');
const dir = path.dirname(fileURLToPath(import.meta.url));
const source = fs.readFileSync(path.join(dir, 'hermes-day-one.md'), 'utf8');
const fence = (s,lang='text') => '\n```'+lang+'\n'+s+'\n```\n';
const commonInstallEnd = source.slice(source.indexOf('### Confirm installation'), source.indexOf('## Track 1:'));
const platforms = {
  linux: {
    label: 'Linux', shell: 'Terminal', fileManager: 'your file manager',
    before: 'Open your Linux terminal. This lane uses Ubuntu/Debian package commands where distribution-specific preparation is needed; other distributions should use their own package manager. A desktop is optional, but browser sign-in requires a browser on this or another device.',
    install: `## Install once\n\nAll four provider tracks use this installation. Run the installer as your normal user.\n\n### 1. Prepare Linux\n\nFor Ubuntu or Debian:\n${fence('sudo apt update\nsudo apt install -y git curl xz-utils','bash')}\nOther distributions: install Git, curl, and the xz tools with your distribution’s package manager. Check Git:\n${fence('git --version','bash')}\n### 2. Install Hermes\n${fence('curl -fsSL https://hermes-agent.nousresearch.com/install.sh | bash','bash')}\nThis downloads and runs the official installer. Follow its prompts, then open a fresh terminal. The installer supplies its other application dependencies. [Linux installation reference](https://hermes-agent.nousresearch.com/docs/getting-started/installation).\n\n`,
    ollama: `Complete [Install once](#install-once). In your Linux terminal, install Ollama:\n${fence('curl -fsSL https://ollama.com/install.sh | sh','bash')}\nOn a systemd machine, check its service:\n${fence('systemctl status ollama --no-pager','bash')}\nIf it is installed but stopped, run \`sudo systemctl start ollama\`. Without a managed service, run \`ollama serve\` and leave that terminal open. Do not start a second server when one is already running. [Ollama Linux instructions](https://docs.ollama.com/linux).`,
    modelfile: fence("mkdir -p ~/hermes-day-one-model\ncd ~/hermes-day-one-model\ncat > Modelfile <<'EOF'\nFROM qwen3.5:9b\nPARAMETER num_ctx 65536\nEOF",'bash'),
    practice: `In Terminal, make and enter a new practice folder:\n${fence('mkdir ~/hermes-day-one-practice\ncd ~/hermes-day-one-practice','bash')}\nIf that folder already exists, use a new folder name for this exercise. We can inspect the result with a file manager, or on a server use \`cat packing-checklist.md\` from a second terminal in this folder.`,
  },
  mac: {
    label: 'Mac', shell: 'Terminal', fileManager: 'Finder',
    before: 'Open Terminal from Applications → Utilities. Check Apple menu → About This Mac for your macOS version, chip, and memory. This lane targets Apple Silicon: Hermes currently lists Intel Macs as unsupported. If yours says Intel, use a supported Linux/Windows computer for this lesson. [Hermes platform support](https://hermes-agent.nousresearch.com/docs/getting-started/platform-support).',
    install: `## Install once\n\nAll four tracks use the same Hermes installation. Choose one method.\n\n### Option A: Desktop download\n\n1. Open the [official Hermes download page](https://hermes-agent.nousresearch.com/).\n2. Choose the Mac installer that matches your computer and complete its prompts.\n3. Open a fresh Terminal window. The installer includes the command-line app, which we use below.\n\n### Option B: Terminal installation\n\nCheck Git:\n${fence('git --version','bash')}\nIf macOS offers to install developer tools, complete that prompt and retry. Then install Hermes:\n${fence('curl -fsSL https://hermes-agent.nousresearch.com/install.sh | bash','bash')}\nThis downloads and runs the official installer. Follow its prompts, then open a fresh Terminal window. [Mac installation reference](https://hermes-agent.nousresearch.com/docs/getting-started/installation).\n\n`,
    ollama: 'Complete [Install once](#install-once), then download [Ollama for Mac](https://ollama.com/download/mac), install it, and open it. This Hermes lane is for Apple Silicon. Ollama currently requires macOS 14 or later and supports CPU/GPU execution on Apple M-series Macs. Check the [current Mac requirements](https://docs.ollama.com/macos).',
    modelfile: fence("mkdir -p ~/hermes-day-one-model\ncd ~/hermes-day-one-model\ncat > Modelfile <<'EOF'\nFROM qwen3.5:9b\nPARAMETER num_ctx 65536\nEOF",'bash'),
    practice: `In Terminal, make and enter a new practice folder:\n${fence('mkdir ~/hermes-day-one-practice\ncd ~/hermes-day-one-practice','bash')}\nIf that folder already exists, use a new folder name. In Finder, Go → Go to Folder lets us open \`~/hermes-day-one-practice\` to inspect the result.`,
  },
  windows: {
    label: 'Windows', shell: 'PowerShell', fileManager: 'File Explorer',
    before: 'Open PowerShell from the Start menu. This lane uses native Windows for both Hermes and Ollama. If you intentionally use WSL2, follow the Linux lane and install both programs there; do not mix its commands with this lane.',
    install: `## Install once\n\nAll four tracks use the same Hermes installation. Choose one method.\n\n### Option A: Desktop download\n\n1. Open the [official Hermes download page](https://hermes-agent.nousresearch.com/).\n2. Download the Windows installer and complete its prompts.\n3. Open a fresh PowerShell window. The installer includes the command-line app, which we use below.\n\n### Option B: PowerShell installation\n\nRun this in PowerShell:\n${fence('iex (irm https://hermes-agent.nousresearch.com/install.ps1)','powershell')}\nThis downloads and runs the official installer. Follow its prompts, then close and reopen PowerShell. Native Windows is now documented; older tutorials may require WSL2. Do not paste the Mac/Linux installer into PowerShell. [Windows installation reference](https://hermes-agent.nousresearch.com/docs/getting-started/installation).\n\n`,
    ollama: 'Complete [Install once](#install-once), then download [Ollama for Windows](https://ollama.com/download/windows) and run its installer. Open Ollama from Start and leave it running in the background. Current requirements include Windows 10 22H2 or newer, with suitable drivers for GPU acceleration. [Windows requirements](https://docs.ollama.com/windows). Use native Windows for both programs in this lane.',
    modelfile: fence("New-Item -ItemType Directory -Force -Path \"$env:USERPROFILE\\hermes-day-one-model\" | Out-Null\nSet-Location \"$env:USERPROFILE\\hermes-day-one-model\"\n@'\nFROM qwen3.5:9b\nPARAMETER num_ctx 65536\n'@ | Set-Content -Encoding ascii Modelfile",'powershell'),
    practice: `In PowerShell, make and enter a new practice folder:\n${fence('New-Item -ItemType Directory -Path "$env:USERPROFILE\\hermes-day-one-practice"\nSet-Location "$env:USERPROFILE\\hermes-day-one-practice"','powershell')}\nIf that folder already exists, use a new folder name. In File Explorer’s address bar, enter \`%USERPROFILE%\\hermes-day-one-practice\` to inspect the result.`,
  }
};
const css = fs.readFileSync(path.join(dir,'guide-theme.css'),'utf8');
fs.writeFileSync(path.join(dir,'guide.css'),css);
const js = `document.querySelectorAll('pre').forEach(pre=>{const button=document.createElement('button');button.type='button';button.textContent='Copy';button.setAttribute('aria-label','Copy this command or prompt');button.addEventListener('click',async()=>{const text=pre.querySelector('code').textContent;try{await navigator.clipboard.writeText(text);button.textContent='Copied';setTimeout(()=>button.textContent='Copy',1800)}catch{const r=document.createRange();r.selectNodeContents(pre.querySelector('code'));const s=window.getSelection();s.removeAllRanges();s.addRange(r);button.textContent='Selected — use Copy'}});pre.appendChild(button)});`;
fs.writeFileSync(path.join(dir,'guide.js'),js);
const slug = text => text.toLowerCase().replace(/[^a-z0-9\s-]/g,'').trim().replace(/\s+/g,'-');
const header = active => `<a class="skip" href="#main">Skip to guide</a><header><a class="brand" href="https://lokislab.org/" aria-label="Loki’s Lab home"><span class="brand-mark" aria-hidden="true"><i>L</i><i>L</i></span><strong>Loki’s Lab</strong></a><nav class="site-nav" aria-label="Loki’s Lab"><a href="https://lokislab.org/">Home</a><a href="https://lokislab.org/test/results">Leaderboard</a><a href="https://lokislab.org/news">News</a><a href="https://lokislab.org/test">Test</a></nav></header><nav class="platforms" aria-label="Operating system"><a href="index.html">Start here</a>${Object.entries(platforms).map(([id,p])=>`<a href="${id}.html" ${id===active?'aria-current="page"':''}>${p.label}</a>`).join('')}</nav>`;
const footer = '<footer>Loki’s Lab · Hermes Day One</footer>';
const page = (title,body,active='') => `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title} | Loki’s Lab</title><link rel="stylesheet" href="guide.css"></head><body>${header(active)}${body}${footer}<script src="guide.js"></script></body></html>`;
for(const [id,p] of Object.entries(platforms)){
  let md = source.replace('# Hermes Day One: Four Ways to Get Started',`# Hermes Day One for ${p.label}`);
  md = md.replace('Our first working assistant, one step at a time.',`Four guided tracks for ${p.label}: Nous, ChatGPT/Codex, Anthropic, and local Ollama.\n\n[Choose a different operating system](index.html).`);
  md = md.replace('- On a Mac, open **Terminal** from Applications → Utilities. On Windows, open **PowerShell** from Start. Terminal commands below go there, not into an AI chat.',`- ${p.before} Commands below go in ${p.shell}, not into an AI chat.`);
  md = md.replace(/## Install once\n[\s\S]*?(?=## Track 1:)/,p.install+commonInstallEnd);
  md = md.replace('Complete [Install once](#install-once), then download and open [Ollama for your operating system](https://ollama.com/download). Keep Hermes and Ollama in the same operating-system environment for this lesson: both native Windows, both on the Mac, or both inside WSL2. Mixing Windows and WSL2 adds a networking step.',p.ollama);
  md = md.replace(/In a new working folder, create a plain-text file[\s\S]*?then run:/,`Run this block in ${p.shell} to create the model configuration in its own folder. It writes a file named \`Modelfile\`:\n${p.modelfile}\nThen run:`);
  md = md.replace(/Create a new empty folder named[\s\S]*?Alternatively, type `cd` followed by the full folder path in quotes\./,p.practice);
  md = md.replaceAll('Finder or File Explorer',p.fileManager).replaceAll('Terminal or PowerShell',p.shell);
  md = md.replace('Open Ollama. If running a CLI-only service, start `ollama serve` in another terminal.',id==='linux'?'Check the Ollama service; without a service, start `ollama serve` in another terminal.':'Open Ollama and leave it running.');
  fs.writeFileSync(path.join(dir,id+'.md'),md);
  const tokens = marked.lexer(md);
  const toc = tokens.filter(t=>t.type==='heading'&&t.depth===2).map(t=>({text:t.text,id:slug(t.text)}));
  let html = marked.parse(md);
  html = html.replace(/<h([123])>(.*?)<\/h\1>/g,(_,level,text)=>`<h${level} id="${slug(text.replace(/<[^>]+>/g,''))}">${text}</h${level}>`).replace(/<table>/g,'<div class="table-wrap"><table>').replace(/<\/table>/g,'</table></div>');
  const body = `<div class="layout"><aside aria-label="On this page"><strong>${p.label} · Jump to a step</strong>${toc.map(t=>`<a href="#${t.id}">${t.text}</a>`).join('')}</aside><main id="main">${html}</main></div>`;
  fs.writeFileSync(path.join(dir,id+'.html'),page(`Hermes Day One for ${p.label}`,body,id));
}
const cards = Object.entries(platforms).map(([id,p])=>`<a class="card" href="${id}.html"><h2>${p.label}</h2><p>${id==='linux'?'Terminal setup, with Ubuntu/Debian preparation.':id==='mac'?'Mac download or Terminal installation.':'Native Windows download or PowerShell setup.'}</p><strong>Choose your provider track →</strong></a>`).join('');
const home = `<div class="home"><main id="main"><p class="eyebrow">A living field guide</p><h1>Our first day<br>with Hermes.</h1><p>Install the assistant. Connect a model. Make something we can open ourselves.</p><p>Choose your operating system, then follow one of four guided tracks. Every lane ends with the same packing-checklist exercise.</p><div class="cards">${cards}</div><div class="note"><strong>Four tracks in every lane</strong><p>01 · Nous account &nbsp; 02 · ChatGPT/Codex login<br>03 · Anthropic API &nbsp; 04 · Local Ollama model</p></div><h2>A guide to keep learning with.</h2><p>Keep your guide open beside your terminal. Each version includes copyable commands, checkpoints, troubleshooting, and official references. The instructions are editable so we can update them as Hermes changes.</p><p><strong>Anthropic note:</strong> The guided route uses an API key. Subscription-login eligibility and billing need verification; the lane explains the published guidance.</p></main></div>`;
fs.writeFileSync(path.join(dir,'index.html'),page('Hermes Day One',home));
console.log('Built three Markdown guides, three HTML guides, and an HTML landing page.');
